name: Deploy Action
on: 
  push:
    branches:
      - main

jobs:
  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.EMAIL }}
          
      - name: "Login to heroku registry"
        run: heroku container:login

      - name: "Build and push to heroku registry"
        run: heroku container:push worker --app ${{ secrets.HEROKU_APP_NAME }}

      - name: "Releases the container"
        run: heroku container:release worker --app ${{ secrets.HEROKU_APP_NAME }}
